### ISSUE TITLE
Modernização Buscador Evid@Easy

### ISSUE THREAD

**Issue by guilhermealves-dev** [bireme/mockups#3]
Arquivos para deploy do Mockup do Buscador Evid@Easy:

[buscador-evideasy.zip](https://github.com/bireme/mockups/files/9901181/buscador-evideasy.zip)

**Comment by marcoslmori** [comment]
publicado em http://mockups.teste.bireme.org/evideasy/

Antiga pagina em http://mockups.teste.bireme.org/evideasy-page/

**Comment by guilhermealves-dev** [comment]
Ajustes em perguntas:

[buscador-evideasy-v2.zip](https://github.com/bireme/mockups/files/9903016/buscador-evideasy-v2.zip)

**Comment by guilhermealves-dev** [comment]
Alterado perguntas e respostas

[buscador-evideasy-v3.zip](https://github.com/bireme/mockups/files/9903307/buscador-evideasy-v3.zip)

**Comment by marcoslmori** [comment]
atualizado em http://mockups.teste.bireme.org/evideasy/

**Comment by guilhermealves-dev** [comment]
Ajuste em tradução de respostas.

[buscador-evideasy-v4.zip](https://github.com/bireme/mockups/files/9904742/buscador-evideasy-v4.zip)
