### ISSUE TITLE
Prints LILACS Plus

### ISSUE THREAD

**Issue by marcioalvessilva** [bireme/mockups#4]
![1](https://github.com/user-attachments/assets/af91ff40-f195-40fd-9aa2-0276275ac806)
![2](https://github.com/user-attachments/assets/b1ceb1ae-3cab-46bf-a2c7-23e1885c113c)
![3](https://github.com/user-attachments/assets/4a4ba606-6fb5-4b60-829a-65decf4e4544)

**Comment by ramosluc** [comment]
Alternativas para alinhamento das abas IAHx, uma utilizando 70% do container e outra com 100% de utilização do container após a retirada da terceira aba.

![localhost_iahx_final_v2_iahx_ alinhamento_esquerda_70%](https://github.com/user-attachments/assets/94a21aa0-745f-4a4c-bd6c-e1c743fee400)
![localhost_iahx_final_v2_iahx_](https://github.com/user-attachments/assets/4c2a8cca-dd8c-4c4d-9a1c-1a5ed4376599)

**Comment by marcioalvessilva** [comment]
Lucas, boa tarde!
Apresente para Rose antes de apresentar para equipe, eu tenho algumas sugestões que talvez sejam uteis
- Acho que falta acabamento (espaço entre texto e número, o ícone também me parece solto e  pequeno - precisa ser testado)
- Procure alguns exemplos de abas, talvez encontre uma boa referencia
- Veja se consegue sugerir um acabamento melhor (Não tenho sugestão no momento)
- Tenta inserir isso em um html para ver o comportamento vai dar certo, considerando que temos dois  pontos de clique (aba e botão).
- Melhor destaque da aba LILACS enquanto ativa

**Comment by marcioalvessilva** [comment]
Etapa concluída!
